timezone: "Europe/Amsterdam"
worldConfig:
    groups:
        default:
            alias: Default
        hardcoreGroup:
            alias: Hardcore Worlds
            worlds:
            - HardcoreWorld
            - HardcoreWorld_nether
            - HardcoreWorld_the_end
            config:
                enabled: true
