name: CustomHardcore
main: org.kepow.customhardcore.CustomHardcore
version: 1.1
description: Customizable per-worldgroup hardcore settings.
author: Beskhue
authors: [Beskhue]
softdepend: [Multiverse-Core]
commands:
  chc:
    description: Perform CustomHardcore commands. Type '/chc' for more information. 
    usage: /chc <command>
permissions:
  customhardcore.*:
    description: Gives access to all CustomHardcore commands and bypasses.
    children:
      customhardcore.info.*: true
      customhardcore.moderator.*: true
      customhardcore.admin.*: true
  customhardcore.info.*:
    description: Gives permission to view hardcore info.
    default: true
    children:
      customhardcore.info.player: true
      customhardcore.info.group: true
      customhardcore.info.list: true
  customhardcore.moderator.*:
    description: Gives permission to perform moderator commands.
    default: op
    children:
      customhardcore.moderator.banish: true
      customhardcore.moderator.unbanish: true
  customhardcore.admin.*:
    description: Gives permission to perform admin commands.
    default: op
    children:
      customhardcore.admin.reload: true
  customhardcore.info.player:
    description: Gives permission to view player hardcore info.
  customhardcore.info.group:
    description: Gives permission to view group hardcore info.
  customhardcore.info.list:
    description: Gives permission to list hardcore groups.
  customhardcore.moderator.banish:
    description: Gives permission to banish players from world groups.
  customhardcore.moderator.unbanish:
    description: Gives permission to unbanish players from world groups.
  customhardcore.admin.reload:
    description: Gives permission to perform admin commands.
    default: op

